### PR TITLE
update about page paragraphs

### PR DESCRIPTION
**Pull request by Jobhdez**
## Motivation and Context

removed old paragraphs and added a new one based on the figma design. Styling is a different issue so I did not style it.

## test
I did `yarn start` and everything looked good.

### CODE REVIEW

**Comment by josueetcom** [comment]
Please be precise about the PR titles. "removed old paragraphs and added new one" is pretty generic. Somebody reading that commit has no idea what paragraphs you're talking about without opening up this PR.

**Review by josueetcom — APPROVED** [review]

**Comment by Jobhdez** [comment]
> Please be precise about the PR titles. "removed old paragraphs and added new one" is pretty generic. Somebody reading that commit has no idea what paragraphs you're talking about without opening up this PR.

do you mean the commit messages? I never explicitly made a PR title.

**Comment by josueetcom** [comment]
> do you mean the commit messages? I have never explicitly made a PR title.

I mean the PR title. It'll take it from your first commit but you can change it to be clearer.

**Comment by Jobhdez** [comment]
> > do you mean the commit messages? I have never explicitly made a PR title.
> 
> I mean the PR title. It'll take it from your first commit but you can change it to be clearer.
Ok I’ll make my commit messages more precise.

**Pull request merged**
