### PR TITLE
Fix broken links

### PR DESCRIPTION
**Pull request by Jobhdez**
## Motivation and Context

renamed the branch. and deleted the firebase stuff. it wasnt needed. i did `yarn start` and everything worked fine.

### CODE REVIEW

**Comment by Jobhdez** [comment]
there was an option to merge with main and i merged it and this resulted in the validation / style and validation / test checks failed. do we have to fix the checks manually?

**Comment by josueetcom** [comment]
> there was an option to merge with main and i merged it and this resulted in the validation / style and validation / test checks failing. do we have to fix the checks manually?

If you manually merged then perhaps the changes affected something. Otherwise you can try re-running the checks (just did that for you)

**Review by josueetcom — APPROVED** [review]

**Comment by josueetcom** [comment]
Btw, please don't create duplicate PRs for the same issue without closing the first one. I approved this assuming it was the other PR but some description comments and issue linking was missing.

**Comment by josueetcom** [comment]
Also there was no need to recreate the branch or the PR. The branch name isn't important, it's the title of the PR and the description that's important because when looking at commit history that's what's going to be seen first.

**Comment by Jobhdez** [comment]
i thought i renamed the issue not create a new branch. sorry

**Comment by Jobhdez** [comment]
I can add a link to the other branch here in the description.

**Pull request merged**
